# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved

from .chart import DensePoseChartLoss
from .chart_with_confidences import DensePoseChartWithConfidenceLoss
from .chart_global_IUV_seperated_S import DensePoseChartGlobalIUVSeparatedSLoss
from .chart_global_IUV_seperated_S_cropResize import DensePoseChartGlobalIUVSeparatedSCropResizeLoss
from .chart_global_IUV_seperated_S_multiscale_cropResize import DensePoseChartGlobalIUVSeparatedSMultiscaleCropResizeLoss
from .chart_global_IUV_seperated_S_pooler import DensePoseChartGlobalIUVSeparatedSPoolerLoss