_BASE_: "Base-DensePose-CondInst.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  CONDINST:
    MASK_BRANCH:
      OUT_CHANNELS: 8 # 104 = 96+8
      # IN_FEATURES: ["p2", "p3", "p4", "p5"]
    IUVHead:
      CHANNELS: 128
      USE_AGG_FEATURES: True
    MASK_HEAD:
      CHANNELS: 8

  
  ROI_DENSEPOSE_HEAD:
    # PREDICTOR_NAME: "DensePoseChartWithConfidencePredictor"
    # LOSS_NAME: "DensePoseChartWithConfidenceLoss"
    PREDICTOR_NAME: "DensePoseChartPredictor"
    LOSS_NAME: "DensePoseChartGlobalIUVSeparatedSLoss"
    NUM_COARSE_SEGM_CHANNELS: 1
SOLVER:
  MAX_ITER: 130000
  STEPS: (100000, 120000)
