_BASE_: "Base-DensePose-CondInst.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  CONDINST:
    MASK_BRANCH:
      OUT_CHANNELS: 8 # 104 = 96+8
    IUVHead:
      CHANNELS: 128
    MASK_HEAD:
      CHANNELS: 8

  
  ROI_DENSEPOSE_HEAD:
    # PREDICTOR_NAME: "DensePoseChartWithConfidencePredictor"
    # LOSS_NAME: "DensePoseChartWithConfidenceLoss"
    PREDICTOR_NAME: "DensePoseChartPredictor"
    LOSS_NAME: "DensePoseChartGlobalIUVSeparatedSLoss"
    NUM_COARSE_SEGM_CHANNELS: 1
# SOLVER:
#   MAX_ITER: 130000
#   STEPS: (100000, 120000)
SOLVER:
  # MAX_ITER: 190000
  # STEPS: (100000, 160000)
  # MAX_ITER: 390000
  # STEPS: (300000, 360000)
  # MAX_ITER: 480000
  # STEPS: (300000, 420000)
  # Start from s1x 99999
  MAX_ITER: 380000
  STEPS: (200000, 320000)
  # MAX_ITER: 480000
  # STEPS: (300000, 420000)
