_BASE_: "Base-DensePose-CondInst.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  BACKBONE:
    NAME: "build_fcos_resnet_bifpn_backbone"
  RESNETS:
    DEPTH: 50
  BiFPN:
    IN_FEATURES: ["res3", "res4", "res5"]
    OUT_CHANNELS: 160
    NORM: "GN" # "SyncBN"

  CONDINST:
    MASK_BRANCH:
      OUT_CHANNELS: 8 # 104 = 96+8
    IUVHead:
      CHANNELS: 128
    MASK_HEAD:
      CHANNELS: 8

  
  ROI_DENSEPOSE_HEAD:
    # PREDICTOR_NAME: "DensePoseChartWithConfidencePredictor"
    # LOSS_NAME: "DensePoseChartWithConfidenceLoss"
    PREDICTOR_NAME: "DensePoseChartPredictor"
    LOSS_NAME: "DensePoseChartGlobalIUVSeparatedSLoss"
    NUM_COARSE_SEGM_CHANNELS: 1
SOLVER:
  MAX_ITER: 130000
  STEPS: (100000, 120000)
