_BASE_: "Base-DensePose-CondInst.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  CONDINST:
    MASK_BRANCH:
      OUT_CHANNELS: 8 # 104 = 96+8
    IUVHead:
      CHANNELS: 128
    MASK_HEAD:
      CHANNELS: 8
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]

  ROI_HEADS:
    NAME: "DensePoseROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: 1
  # ROI_BOX_HEAD:
  #   NAME: "FastRCNNConvFCHead"
  #   NUM_FC: 2
  #   POOLER_RESOLUTION: 7
  #   POOLER_SAMPLING_RATIO: 2
  #   POOLER_TYPE: "ROIAlign"
  ROI_DENSEPOSE_HEAD:
    NAME: "DensePoseV1ConvXHead"
    POOLER_TYPE: "ROIAlign"
    NUM_COARSE_SEGM_CHANNELS: 2
  
SOLVER:
  MAX_ITER: 130000
  STEPS: (100000, 120000)
