source ~/.bashrc_liqianma

# cfg_name='densepose_CondInst_R_101_s1x'
# CUDA_LAUNCH_BLOCKING=1 python train_net.py --config-file configs/${cfg_name}.yaml \
# 	--resume \
#     SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025 \
#     OUTPUT_DIR ./output/${cfg_name}_1chSeg_RelCoordDetach \
#     MODEL.ROI_DENSEPOSE_HEAD.NUM_COARSE_SEGM_CHANNELS 1 \
#     MODEL.ROI_DENSEPOSE_HEAD.COARSE_SEGM_TRAINED_BY_MASKS True \
#     SOLVER.CHECKPOINT_PERIOD 2000 \
#     MODEL.ROI_DENSEPOSE_HEAD.REL_COORDS True \
#     DATALOADER.NUM_WORKERS 2 \
#     # MODEL.CONDINST.IUVHead.NUM_CONVS 7 \
#     # MODEL.ROI_DENSEPOSE_HEAD.INDEX_WEIGHTS 3.0 \
#     # MODEL.WEIGHTS ../../pretrain/CondInst_MS_R_101_3x_sem.pth \
#     # MODEL.CONDINST.MASK_BRANCH.NORM "BN"\
#     # MODEL.ROI_DENSEPOSE_HEAD.POINT_REGRESSION_WEIGHTS 3.0 \
#     # MODEL.ROI_DENSEPOSE_HEAD.INDEX_WEIGHTS 0.
#     # DATALOADER.NUM_WORKERS 1 \

# cfg_name='densepose_CondInst_R_50_s1x'
# CUDA_LAUNCH_BLOCKING=1 python train_net.py --config-file configs/${cfg_name}.yaml \
# 	--resume \
#     SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025 \
#     OUTPUT_DIR ./output/${cfg_name}_1chSeg_uvMean_cropResize_deepIUVHead \
#     MODEL.ROI_DENSEPOSE_HEAD.NUM_COARSE_SEGM_CHANNELS 1 \
#     MODEL.ROI_DENSEPOSE_HEAD.COARSE_SEGM_TRAINED_BY_MASKS True \
# 	MODEL.ROI_DENSEPOSE_HEAD.POINT_REGRESSION_WEIGHTS 1.0 \
#     SOLVER.CHECKPOINT_PERIOD 5000 \
#     DATALOADER.NUM_WORKERS 2 \
# 	MODEL.ROI_DENSEPOSE_HEAD.LOSS_NAME "DensePoseChartGlobalIUVSeparatedSCropResizeLoss" \
# 	MODEL.CONDINST.IUVHead.NUM_CONVS 7 \
# 	# MODEL.ROI_DENSEPOSE_HEAD.NAME "DensePoseDeepLabHead" \
# 	# MODEL.ROI_DENSEPOSE_HEAD.REL_COORDS True \

# cfg_name='densepose_CondInst_R_50_s1x'
# CUDA_LAUNCH_BLOCKING=1 python train_net.py --config-file configs/${cfg_name}.yaml \
# 	--resume \
#     SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025 SOLVER.WARMUP_ITERS 4000 \
#     OUTPUT_DIR ./output/${cfg_name}_1chSeg_cropResize_deepLabHead_warmup4k \
#     MODEL.ROI_DENSEPOSE_HEAD.NUM_COARSE_SEGM_CHANNELS 1 \
#     MODEL.ROI_DENSEPOSE_HEAD.COARSE_SEGM_TRAINED_BY_MASKS True \
#     SOLVER.CHECKPOINT_PERIOD 1000 \
#     DATALOADER.NUM_WORKERS 2 \
# 	MODEL.ROI_DENSEPOSE_HEAD.LOSS_NAME "DensePoseChartGlobalIUVSeparatedSCropResizeLoss" \
# 	MODEL.ROI_DENSEPOSE_HEAD.NAME "DensePoseDeepLabHead" \
#     # MODEL.CONDINST.IUVHead.NUM_LAMBDA_LAYER 1 \
# 	# MODEL.ROI_DENSEPOSE_HEAD.POINT_REGRESSION_WEIGHTS 1.0 \
# 	# MODEL.CONDINST.IUVHead.NUM_CONVS 7 \
# 	# MODEL.ROI_DENSEPOSE_HEAD.REL_COORDS True \


cfg_name='densepose_CondInst_R_50_s1x'
CUDA_LAUNCH_BLOCKING=1 python train_net.py --config-file configs/${cfg_name}.yaml \
	--resume \
    SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025 \
    OUTPUT_DIR ./output/${cfg_name}_1chSeg_cropResizeNew_deepIUVHead \
    MODEL.ROI_DENSEPOSE_HEAD.NUM_COARSE_SEGM_CHANNELS 1 \
    MODEL.ROI_DENSEPOSE_HEAD.COARSE_SEGM_TRAINED_BY_MASKS True \
    SOLVER.CHECKPOINT_PERIOD 5000 \
    DATALOADER.NUM_WORKERS 2 \
	MODEL.ROI_DENSEPOSE_HEAD.LOSS_NAME "DensePoseChartGlobalIUVSeparatedSCropResizeLoss" \
	MODEL.CONDINST.IUVHead.NUM_CONVS 7 \
    # SOLVER.CLIP_GRADIENTS.ENABLED True \
	# MODEL.ROI_DENSEPOSE_HEAD.NAME "DensePoseDeepLabHead" \
	# MODEL.ROI_DENSEPOSE_HEAD.POINT_REGRESSION_WEIGHTS 1.0 \
	# MODEL.ROI_DENSEPOSE_HEAD.REL_COORDS True \
	# SOLVER.WARMUP_ITERS 2000
    # SOLVER.CLIP_GRADIENTS.ENABLED True SOLVER.CLIP_GRADIENTS.CLIP_TYPE norm SOLVER.CLIP_GRADIENTS.CLIP_VALUE 100.0\


# cfg_name='densepose_CondInst_R_101_s1x'
# CUDA_LAUNCH_BLOCKING=1 python train_net.py --config-file configs/${cfg_name}.yaml \
# 	--resume \
#     SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025 \
#     OUTPUT_DIR ./output/${cfg_name}_1chSeg_noIUVLoss \
#     MODEL.ROI_DENSEPOSE_HEAD.NUM_COARSE_SEGM_CHANNELS 1 \
#     MODEL.ROI_DENSEPOSE_HEAD.COARSE_SEGM_TRAINED_BY_MASKS True \
#     MODEL.ROI_DENSEPOSE_HEAD.POINT_REGRESSION_WEIGHTS 0. \
#     MODEL.ROI_DENSEPOSE_HEAD.PART_WEIGHTS 0. \
#     # MODEL.ROI_DENSEPOSE_HEAD.INDEX_WEIGHTS 1.0 \
#     # MODEL.ROI_DENSEPOSE_HEAD.INDEX_WEIGHTS 0.
#     # MODEL.WEIGHTS ./output/${cfg_name}/model_0129999.pth \
#     # DATALOADER.NUM_WORKERS 1 \