_BASE_: "Base-DensePose-CondInst.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  CONDINST:
    MASK_BRANCH:
      OUT_CHANNELS: 104 # 104 = 96+8
    IUVHead:
      CHANNELS: 96
    MASK_HEAD:
      CHANNELS: 8
SOLVER:
  MAX_ITER: 130000
  STEPS: (100000, 120000)
